
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    environment:
      - ConnectionStrings:DefaultConnection=Server=db;Database=master;User Id=sa;Password=YourStrongPassword!;
      - ACCEPT_EULA=Y
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./AspNetApp:/app/src
    command: dotnet watch run --urls http://+:8080

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest" 
    container_name: sql_server_db
    environment:
      SA_PASSWORD: "YourStrongPassword!" 
      ACCEPT_EULA: "Y" 
    ports:
      - "1433:1433" 
    volumes:
      - sql_server_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_server_data: